# Generated by Django 4.2.1 on 2023-06-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myuser',
        ),
    ]
