# Generated by Django 4.2.1 on 2023-06-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
        ),
    ]
